### ISSUE TITLE
Feature request: Offline/Online detection for mobile devices (Mobile Safari / Mobile Chrome)

### ISSUE THREAD

**Issue by inglesuniversal** [localForage/localForage#1012]
Hi, is there a way to add a feature to detect user online presence and handle online of offline events of users?

Best regards

**Comment by UnKnoWn-Consortium** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events

**Comment by thgreasi** [comment]
@inglesuniversal online/offline detection is out of scope for this library, since LocalForage is only focused on storing data locally.
Such network state detection is completely out of scope.
Using browser API's or periodically pinging a specific endpoint on a server that you can trust might be the best option for your use case.
