### ISSUE TITLE
Where is the 2.0 release?

### ISSUE THREAD

**Issue by Rush** [localForage/localForage#1015]
On May, 2018 a memory driver was merged https://github.com/localForage/localForage/pull/555#issuecomment-392352127 but it's still not available in the official npm package.

**Comment by tofumatt** [comment]
That was merged into a 2.0-dev branch but it's a bit old at this point...

The existing codebase is actually a bit old and unwieldy, so I'm actually working on a near top-to-bottom refactor/rewrite in TypeScript that includes that feature and more: #906.

But localForage is something I can only work on sometimes due to other commitments.

In the meantime, we do support custom backends, so you can load the memory driver into your own localForage in the meantime. 🙂
