### ISSUE TITLE
[Feature Request] Support GreaseMonkey API GM.addValue & GM.setValue etc. as backend

### ISSUE THREAD

**Issue by SukkaW** [localForage/localForage#1016]
RT.

I am willing to create a Pull Request implementing feature.

**Comment by tofumatt** [comment]
This isn't something we would integrate into localForage core because it's a very limited-use API that isn't generic to web browsers. But we do support custom drivers: https://localforage.github.io/localForage/#driver-api-definedriver

You can create your own driver and offer it to others for this purpose. Once it's ready, feel free to open a PR against this repo's README and we can link to your driver! 👍🏻
