### ISSUE TITLE
react-native 0.69.1 - Error: No available storage method found.

### ISSUE THREAD

**Issue by megacherry** [localForage/localForage#1064]
I've updated react-native to 0.69.1 and after that i get the following error: "Error: No available storage method found."

I'm using the driver from https://github.com/aveq-research/localforage-asyncstorage-driver. I don't know if it's related here or in the other repository.

My code looks like:

```
import {driverWithDefaultSerialization} from '@aveq-research/localforage-asyncstorage-driver'
import localforage from 'localforage'

...

const initLocalForage = async () => {
    const driver = driverWithDefaultSerialization()
    await localforage.defineDriver(driver)
    await localforage.setDriver(driver._driver)
    localforage.config()
  }
```

It worked before with react-native 0.68.2.

**Comment by derHodrig** [comment]
I use it in Angular 14 and having same issues, but only in firefox. Chrome and chromium Browsers are all fine.

**Comment by tofumatt** [comment]
I think this would be an upstream issue with `@aveq-research/localforage-asyncstorage-driver`, because localForage itself, using the default drivers, is still working. Can you check with the upstream package, since we don't have any drivers that support React Native built into the localForage core package.
