### ISSUE TITLE
Is this still supported? It has been 3 years?

### ISSUE THREAD

**Issue by billnbell2** [localForage/localForage#1108]

**Comment by rap2hpoutre** [comment]
Seems it's not. Looking for alternative...

**Comment by geoidesic** [comment]
Oh dear. And I'm still using this.

**Comment by Querela** [comment]
Works well enough for me?

Btw, what kind of question is that anyway? Just because there has not been any visible activity does not mean it stops working. And since it is open source, you can always contribute, fork etc. yourself. Issues of this kind with this passive aggressive tone are a bit offensive for developers / maintainers. 😒  Look what happened with the `xz` backdoor ...
If you create an issue like this at least take the time to thank the developer for his effort until now (e.g., if you are already using this library), describe why you need active support (e.g., missing features, open bugs, just emotional support and a warm feeling feeling when you notice some recent changes?) and maybe offer to help ...

**Comment by billnbell3** [comment]
I tried to get it to work and had problems with latest builds of React 18 and NextJS and Safari. I do think it is a great idea to expose this instead of just pumping data into LocalStorage.

**Comment by masudhossain** [comment]
I'm currently looking for an alternative at this point. The race conditions are killing the experience.

**Comment by geoidesic** [comment]
> I'm currently looking for an alternative at this point. The race conditions are killing the experience. 

I haven't encountered any; race conditions nor alternatives.

**Comment by intercepted16** [comment]
Yeah, it seems as if it is not longer maintained. Maybe someone could fork it and continue the project?

**Comment by MohitBansal321** [comment]
but there is no project maintainer maybe

**Comment by pablodz** [comment]
+

**Comment by tofumatt** [comment]
Hi there, "maintainer" of localForage here.

localForage is largely feature-complete, and functions well-enough for many use-cases.

I had planned a TypeScript rewrite that would focus on IndexedDB and localStorage only, but it has been sidelined by my own apps (Electron + Swift, not involving web apps) and contracting work.

I'm not an active user of localForage these days. Of course, people are welcome to fork the repo and such. I've considered marking it as archived as I don't see myself having time to work on it more. Frankly: it seems that these days, using IndexedDB directly or localStorage directly works fine, but I'm also not building offline-first web apps these days.

But I think it's obvious from the repo it is minimally/unmaintained. It should still work though 😅

**Comment by lopugit** [comment]
@tofumatt nice username btw.

Do you recommend any alternatives? 

Otherwise all good 🙌🙌
