### ISSUE TITLE
private mode issue

### ISSUE THREAD

**Issue by pgherveou** [localForage/localForage#145]
Hello there

On Safari (Version 7.0.3) When I activate private mode non of the promise handlers get called.

I tested the following from the console after loading `http://localhost:3000/test/test.html`

``` js
localforage.setItem('foo', 'bar').then(
  function(res) { console.log('ok', res) },
  function(err) { console.log('ko', err) }
);
```

**Comment by tofumatt** [comment]
Could you check to see if #448 helps at all? Using the latest version of master branch should allow you to test.

Hoping we can close this :smile:

**Comment by JustinDrake** [comment]
LocalStorage is still failing in private mode on Safari.

**Comment by tofumatt** [comment]
Unfortunately private mode is not supported by localforage. It shouldn't cause the site to break but saving data in private browsing, even temporarily, doesn't work 😟

**Comment by thgreasi** [comment]
Since we can't do a lot about the storage methods that each browser may or may not provide in private browsing mode, (breath)
how about suggesting to use the [memoryStorageDriver](https://github.com/localForage/localForage-memoryStorageDriver) as a last resort and close this issue?
Localforage should fallback to the memoryStorageDriver and the API we all love will continue to retrieve data, despite that they will be gone after the private browsing session ends.

**Comment by JustinDrake** [comment]
@tofumatt: I know that IndexedDB works in offline mode, so in theory localforage could use that.

**Comment by thgreasi** [comment]
@JustinDrake  What's the result of running [this](http://codepen.io/thgreasi/pen/ojYKeE) example under safari?

**Comment by JustinDrake** [comment]
![screen shot 2017-03-30 at 16 18 56](https://cloud.githubusercontent.com/assets/731743/24511786/9a6e0472-1564-11e7-819e-d5a71f27dc9f.png)

**Comment by thgreasi** [comment]
This pen uses localforage v1.5 which enables IndexedDB for safari v10.2+ .
If you are on safari < 10.2, then IndexedDB is not used because safari's implementation had some issue.
If you are on safari 10.2 and IndexedDB is not used in private mode, then I guess that safari doesn't provide it to be used under private mode.
Please elaborate.

**Comment by JustinDrake** [comment]
I'm using Safari Version 10.0.3. But I think version 10.1 is that latest stable release. Do you mean version 10.0.2?

**Comment by tofumatt** [comment]
I think I've mentioned before but yeah I'm cool with including memoryStorage driver at this point.

**Comment by thgreasi** [comment]
Agreed

**Comment by thgreasi** [comment]
@JustinDrake my bad #650 & #651 mention 10.1+. Sorry for posting wrong version numbers.

**Comment by jancama2** [comment]
@thgreasi How does it look like with release of this feature? The current version is 1.7.3 today, this PR is 2 years old. Would it be possible to add this PR to some 1.*.* version so we all can benefit from the memory driver? 

I'm using `localForage` in couple of my packages and this issue started to be crucial for me as it crashes my app in FF private mode.

I could implement the memory driver for all my packages but it would be nicer to have it directly in `localForage` :).
