### ISSUE TITLE
Make localForage observable 

### ISSUE THREAD

**Issue by iamolivinius** [localForage/localForage#244]
Correct me if I'm wrong but I dont see any convenient way to register callbacks to localForage which are executed when a storage changed.

Are there any plans to provide/merge such a feature?

**Comment by no-more** [comment]
Hello,

Is there any solution to this currently? I would like to use this with angular2 and observable it would be great if this app could support observable.

Thanks.

**Comment by thgreasi** [comment]
Would a simple publish-subscribe implementation suffice for this? Of course
this would only work in the same window/runtime context ( not between two
different instances of the page ).
If that's the case, we could perhaps create an add-on that would
publish/trigger events for all the CRUD operations. That way we can keep
the core implementation simple and lightweight.

Any suggestions on the API? Eg:
localforage.subscribe('setItem', callback );
// OR
localforage.subscribe('myItemKey', callback );

Perhaps we could have two separate methods for localforage-method or
item-key subscriptions.
Waiting for feedback!

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by nolanlawson** [comment]
This is actually something that's not technically feasible right now, at least with IndexedDB and WebSQL. It _does_ work with LocalStorage, so as a hacky workaround you can actually just toggle a key on LocalStorage whenever something changes, and then LocalStorage [emits an event](https://www.w3.org/TR/webstorage/#the-storage-event), which means you can also communicate across tab boundaries this way.

OTOH you may want to wait, because they're actually in the process of adding event listeners to the IDB spec. There's a draft proposal somewhere, but I can't seem to find the link now, but @drufball would know where to find it.

**Comment by thgreasi** [comment]
How about initially making localforage instances observable, so that parts
(of the same page) can subscribe for changes on specific item keys? Would
that be useful to anyone?
At a later point of time (when the new specs and browser support align) we
could also support listening for db changes from different page instances.
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by no-more** [comment]
Hi,

Thanks that would be great. I hope browser will implement this soon.

**Comment by thgreasi** [comment]
Any preference on any Observable library to use? I guess vanilla js folks
would prefer zen-observable but Angular 2 users would probably like RxJ
more.

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Just pushed some commits to my [localForage-observable](
https://github.com/thgreasi/localForage-observable) repo. By default it
uses es-observables but can also be configured to use RxJS as well. Waiting
for your feedback.
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by no-more** [comment]
Hi,
Thanks a lot, I won't be able to try before next week but it looks great
.

**Comment by maysale01** [comment]
@thgreasi Does this work for multiple tabs or windows or is this limited to a single instance?

**Comment by thgreasi** [comment]
@maysale01 no, it doesn't work across tabs, only on the same instance. Like @nolanlawson said a few comments before, it isn't technically possible atm. I may add his hacky localStorage suggestion in some later release though.

**Comment by dmurph** [comment]
Cross-tab observation might be a thing if we do this:
https://github.com/dmurph/indexed-db-observers/blob/gh-pages/EXPLAINER.md
(examples here): https://github.com/dmurph/indexed-db-observers/issues/24

**Comment by thgreasi** [comment]
Just opened localForage/localForage-observable#5 to track the cross-tab support.

**Comment by tofumatt** [comment]
The plugin allows using observable, please follow https://github.com/localForage/localForage-observable/issues/5 for cross-tab support 😄

**Comment by thgreasi** [comment]
Just opened localForage/localForage-observable#6 for this. Any feedback would be great and could help releasing it during the weekend.
