### ISSUE TITLE
Move to using custom driver API to implement our default drivers

### ISSUE THREAD

**Issue by tofumatt** [localForage/localForage#296]
It seems there is no reason we shouldn't be using `defineDriver()` ourselves to implement the default localForage drivers. When we check to make sure a user isn't overwriting a driver, we can just check against drivers defined by localForage on start _and_ the user.

I figure this might clean up the code a bit?

**Comment by SunboX** [comment]
That would be nice for extension developers to look at "how it works" and to prove "that it works". :smile:

**Comment by thgreasi** [comment]
> "how it works" and to prove "that it works"

Custom driver examples can be found at:
* [test/dummyStorageDriver.js](https://github.com/mozilla/localForage/blob/master/test/dummyStorageDriver.js)
* [localForage wiki](https://github.com/mozilla/localForage/wiki/Custom-Drivers)


> will doing this simplify the code enough to justify the work?

The only difference with custom drivers is in [the way we require the driver](https://github.com/mozilla/localForage/blob/90dd7f0825057f14e14377576149b47d84f6daa0/src/localforage.js#L329-L359):
In case we are trying to setup one of the included drivers,
then localforage knows how to require the driver object by itself,
otherwise we expect that the driver object is already defined earlier.

* The Custom Driver architecture currently does not mess with including/requiring the driver itself. Drivers should be defined before trying to use them (even if at end the browser does not support them). The blame is to the user if an unsupported driver is (down)loaded even if it can't be used.
* Built-in drivers are only required/downloaded only if they can actually be used (benefit for requirejs users). This is achieved by including some small [driver support detection tests inside locaforage.src](https://github.com/mozilla/localForage/blob/90dd7f0825057f14e14377576149b47d84f6daa0/src/localforage.js#L329-L359).

A possible refactor could be:

```js
var driverPromise = isLibraryDriver(driverName) ? 
    new Promise(function(resolve/*, reject*/) {
        // require native driver here... the known way...
    }).then(function(driver) {
        return self.defineDriver(driver);
    }) :
    Promise.resolve();

driverPromise.then(function() {
    if (CustomDrivers[driverName]) { // rename this to DefinedDrivers
        self._extend(CustomDrivers[driverName]);
        resolve();
    } else {
        self._driverSet = Promise.reject(error);
        reject(error);
    }
});
```

Removed:
* an `else if()` statement
* an `self._extend()` call
* a `resolve()` call

Added:
* a ternary operator
* we now use the driver holder object for all cases.

**Comment by thgreasi** [comment]
I think that we might have to start working on this. This would also allow us to override the `support` check for the internal drivers, eg letting our user (and namely the Ionic guys) to upgrade to v1.5 and avoid the breaking safari indexeddb change by assigning the v1.4 indexeddb detection code in the `support` property.

@tofumatt @jesusbotella @danielsogl @jgw96
See: https://github.com/ionic-team/ionic-storage/pull/101
