### ISSUE TITLE
Localforage inside webworker for iOS safari

### ISSUE THREAD

**Issue by GeorgeCrecoukias** [localForage/localForage#541]
Hello,

I noticed that in an iOS webworker, getItem will never result in success or an error and throw no exceptions. After some investigation it looks like indexedDB and openDatabase are not available within the worker.

Am I doing something wrong or is webSQL not supported in a webworker for iOS at all? I know indexedDB is not. Outside the worker it picks webSQL and works fine.
Using localForage 1.4 and iOS 9.2.1

**Update**
I found this...
https://bugs.webkit.org/show_bug.cgi?id=149953
https://bugs.chromium.org/p/chromium/issues/detail?id=434740#c4

So I'm probably not doing something wrong, instead webSQL was removed from workers for all webkit browsers and safari didn't replace it with indexeddb.

Thanks.

**Comment by nolanlawson** [comment]
Since iOS WKWebView doesn't support any of LocalStorage/WebSQL/IndexedDB in a worker, unfortunately this is not possible given the current LocalForage implementation.

My advice is to avoid Web Workers in Safari if you need to use IndexedDB/WebSQL. I solved this same problem in my [Pokedex.org](http://www.pocketjavascript.com/blog/2015/11/23/introducing-pokedex-org) app using [pseudo-worker](https://github.com/nolanlawson/pseudo-worker). I.e. you can UA-sniff for Safari (or test if `typeof indexedDB === 'undefined'` in a worker) and then sub in pseudo-worker.

**Comment by GeorgeCrecoukias** [comment]
Sounds good, 
I'm using pseudo-worker and it seems to be working fine.

**Comment by tofumatt** [comment]
Cool, sounds like this is worth noting in some docs.

**Comment by splodingsocks** [comment]
According to https://nolanlawson.github.io/html5workertest/ Safari 10 on both mobile and desktop support IndexedDb in Web Workers. Should that fix this issue?

**Comment by tofumatt** [comment]
Yeah, looks like every browser at least supports IndexedDB in web workers now. We only support IndexedDB in Safari 10.1+, but it should work. I think we can close this now.
