### ISSUE TITLE
Add typescript definitions to the repo

### ISSUE THREAD

**Issue by whitecolor** [localForage/localForage#600]
Why not add type definition directly in the repo and package for God's sake and great goodness?

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10859

**Comment by thgreasi** [comment]
I'm totally fine with such an idea. @tofumatt what's your call? Such a thing would allow us to avoid downloading the huge DefinitelyTyped repo every time we need to make a change. Alternatively we could create a separate localforage.d.ts repo.

PS: atm I'm thinking of incorporating the `export =` syntax in the typings, just like how pouchdb did. CC: @nolanlawson

**Comment by tofumatt** [comment]
Sounds fine to me, though I could certainly comment more if I saw a PR.

But I assume it's just a file that goes in the root of the project? I'm just not a typescript user, so if it has to be maintained someone would need to document how to do that 😄

**Comment by whitecolor** [comment]
@tofumatt yes its just a file and "types" filed in `package.json`

@thgreasi 
> PS: atm I'm thinking of incorporating the export = syntax in the typings, just like how pouchdb did.

will you able to accomplish this with PR?

You also have this nice plugins (setItems, getItems, removeItems) https://github.com/localForage
I'm not sure how they should play and could they extend with localforage typings.

**Comment by tofumatt** [comment]
Cool then, works for me!

**Comment by thgreasi** [comment]
@whitecolor What troubles me is how the various localforage-extensions will be able to reference the `localforage.d.ts` (eg a custom driver should be able to reference the `LocalForageDriver` type), since the [`Typings for NPM Packages` docs](https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html#your-definition-files-should) state that:
> Your definition files should ... not contain triple-slash references.

In the case of DefinitelyTyped, that was not a problem since all the definition folders are defined next to each other. Any ideas?

**Comment by whitecolor** [comment]
@thgreasi 
> Your definition files should ... not contain triple-slash references.
Triple slashes seems to me obsolete 

I asked the question here:
https://github.com/Microsoft/TypeScript/issues/10635

> What troubles me is how the various localforage-extensions will be able to reference the localforage.d.ts

I my view it should be done just:
```js
import {LocalForageDriver, localforage} from 'localforage'
```
It is achieved by just exporting interfaces/types

**Comment by thgreasi** [comment]
Opened PR #611 for this.

**Comment by Elephant-Vessel** [comment]
Could you add the type definitions to @types instead? Today there is some assumptions build into type resolution that assumes that these are in @types: 

https://github.com/Microsoft/TypeScript/issues/20367#issuecomment-348263469
> /// < reference types="request" /> has a specific meaning today. it knows it needs to look in @types packages.

I have a package that has a type-dependency on LocalForage, and the compiler is not generating the type dependency (by using [<reference types...](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)), which as far as I understand is because the types for LocalForage are not found in @types. This means that I have to manually add this every time I recompile my project.

**Comment by tofumatt** [comment]
@Elephant-Vessel Could you file a new issue to get the types added to the types repo and documentation on how to do that? I'm sure someone would take it on but I'm not familiar with the process so I don't really understand the procedure to get that done.

**Comment by thgreasi** [comment]
They had LF typings until recently and I trying to keep them up to date but they [ended up removing them as part of their process](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14860). As a result, I'm not sure whether they would re-add LF typings now that we embed our own typings in the npm module.
