### ISSUE TITLE
Typescript section seems to be outdated?!

### ISSUE THREAD

**Issue by iamolivinius** [localForage/localForage#605]
The typescript section in the README file seems to be outdated. I don't have any issues importing localforage using the ES6 modules syntax. The latest commit from @thgreasi might be the reason for that. 

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/eaeea6e83fc58f97a789813de62e8a387dd5fe97

I tested it with TS 1.8 as well as 2.0.

**Comment by thgreasi** [comment]
Are you getting proper type detection on your import?
After a detailed research in the Typescript docs, this was the only way to make it work on [this sample localForage-cordovaSQLiteDriver Ionic2 project](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonic2App) with proper type detection.
I'm reading that typescript 2.0 now supports `import as namespace` syntax as well, which is ideal for UMD packages like localforage, but back in 1.8 I couldn't find a better way to to it.
What's your suggestion? How about opening a PR on the aforementioned example Ionic 2 repo, so that I can check it out?

**Comment by thgreasi** [comment]
Related to #602

**Comment by thgreasi** [comment]
Ok, so it seems that when using the  `export =` syntax, this one works just like the `import = require()` syntax. I guess that we should advertise the ES6 syntax since it's more elegant.

I'm not sure what to blame, me, the weather or the sublime typescript plugin... I did spent a LOT of time back then and now, without any change, neither on the npm modules nor the typings (but the sublime typescript plugin might got an update), the obviously cleaner code that you suggested works great (with type recognition) along with the `export =` syntax of the typings.

For the record I'm testing this on Ionic 2 with Typescript 1.8.
