### ISSUE TITLE
Possibly unhandled promise in .config()

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#634]
@tofumatt now that I started looking for unhandled promises, I just came by [this one in `config()`](https://github.com/localForage/localForage/blob/4fe872cf0f866cb5bcc54848ecbdfb44915bfd08/src/localforage.js#L153).
What do you think we should do? Should we:
* silence it with a `catch()` like we did with the constructor
* return that promise if a `driver` is passed (which is still truthy, so it's probably not breaking)
* other thing that I couldn't think of since its early in the morning

**Comment by tofumatt** [comment]
Returning it with a `driver` if passed seems to make sense to me, I think you're right that it's not breaking but shouldn't silence an error.

If there's an error from `setDriver` and we return that promise it should expose the `setDriver` error, right? If so that works, otherwise maybe return it but do a `catch()` in there as well.
