### ISSUE TITLE
Change drivers order

### ISSUE THREAD

**Issue by hzlmn** [localForage/localForage#663]
Hi, thanks for good tool.
I just was wondering if there is a way in current `API` to change  default `drivers` order? 

```
By default, localForage selects backend drivers for the datastore in this order:
IndexedDB
WebSQL
localStorage
```
For example I want to change to check WebSQL availability first and then IndexedDB but don't want to force usage of specific one with `setDriver`

Thanks

**Comment by thgreasi** [comment]
`setDriver` can also accept an array of driver names as a parameter. Actually that's exactly [what we are doing internally during initialization](https://github.com/localForage/localForage/blob/1ed5d210fc59c4e60e43d2da76f162e7c82d49f4/src/localforage.js#L119).

Unfortunately, since the `DefaultConfig` object is not exported, you will have to use `setDriver(['WebSQL', 'IndexedDB', 'localStorage'])` on every created instance (or even better, you can pass the preferred driver order as a parameter to [`createInstance({ driver: ['WebSQL', 'IndexedDB', 'localStorage'] })`](https://github.com/localForage/localForage/blob/1ed5d210fc59c4e60e43d2da76f162e7c82d49f4/src/localforage.js#L376)).
