### ISSUE TITLE
null question

### ISSUE THREAD

**Issue by mackelito** [localForage/localForage#667]
Im not sure if this is expected but I keep getting "null" if the Item does not exists.. ?
I have cleared chrome storage to be sure.. there is no data in indexedDB! :P

```javascript
localforage.getItem('auth').then(function(value) {
        console.log('value');
        console.log(value);
    }).catch(function(err) {
        console.log('err');
        console.log(err);
        this.getToken();
    });
```

If I set data then I get the object as expected..

**Comment by tofumatt** [comment]
I think you're expecting to get `undefined`, correct? Yes, returning `null` instead of `undefined` is expected (see https://localforage.github.io/localForage/#data-api-getitem), the reason is that for compatibility across drivers, where `localStorage` can't store `undefined`, we just always cast `undefined` to `null`. It's annoying but better than different engines returning differing results 😒 

Hope that helps, feel free to reopen the issue if I misunderstood 😄

**Comment by mackelito** [comment]
Ah.. haha.. never mind... just crapy coding on my end ;)
