### ISSUE TITLE
typings : Duplicate identifier 'export='.

### ISSUE THREAD

**Issue by Jmadih** [localForage/localForage#680]
After updating my Angular CLI to 1.0.0 i've got those errors :

ERROR in .../node_modules/localforage/typings/localforage.d.ts (113,5): Duplicate identifier 'export='.

ERROR in .../node_modules/@types/localforage/index.d.ts (7,5): Subsequent variable declarations must have the same type.  Variable 'driver' must be of type 'string | s
tring[]', but here has type 'string | LocalForageDriver | LocalForageDriver[]'.
..../node_modules/@types/localforage/index.d.ts (114,5): Duplicate identifier 'export='.

**Comment by thgreasi** [comment]
As with localforage v1.5 you no longer need to user @types definition of localforage, since they are now part of the library itself. Just delete the `node_modules/@types/localforage/` folder and you will be ready to go.
In case that you are using an other library that depends on localforage v1.4 & the @types definitions and you don't like to manually touch the node_modules folder, you will have to wait them to upgrade to localforage v1.5 and drop the @types dependencies.
Closing this for now, please feel free to reopen in any case.

**Comment by Jmadih** [comment]
It works ! Thank you @thgreasi
