### ISSUE TITLE
 Module '"localforage"' has no default export. | localForage, Angular 2 Webpack

### ISSUE THREAD

**Issue by kaleemullah360** [localForage/localForage#689]
trying to use `localForage` library and install via following [tutorial](https://www.thepolyglotdeveloper.com/2016/08/use-mozillas-localforage-key-value-storage-ionic-2/) on importing and compiling it raises error 
> user.service.ts (7,8): Module '"localforage"' has no default export.

I can't make a default export in `SystemJs` cause I am using Webpack.

please help me.

**Comment by thgreasi** [comment]
That's an old enough tutorial.
* Have you tried importing as shown in [README](https://github.com/localForage/localForage/blob/master/README.md#typescript)? I wouldn't use `require()` since in the latest versions of typescript and angular `import` works great.
* Take a look at [this repo](https://github.com/thgreasi/localForage-cordovaSQLiteDriver-TestIonic2App)
* You can also try using ionic-storage, which is actually just a localforage wrapper with a bit different API.

Feel free to re-up if you face any issues.
