### ISSUE TITLE
Safari and multiple instances

### ISSUE THREAD

**Issue by chrisschaub** [localForage/localForage#699]
When I create a localdb, I specify the "name" parameter. In Chrome, if the db exists, specifying the same name as an existing indexdb database opens that database on page reload. In Safari 10.1 on osx, and I think iOS as well, another indexdb is created -- with the exact same name. I have two indexdb datastores in safari, same names, only one on chrome.

**Comment by thgreasi** [comment]
Hi there. Never heard something like that before! What version of localforage after you using?

**Comment by thgreasi** [comment]
Closing this b/c of inactivity. Feel free to re-open if the issue persists.

**Comment by pieisgood** [comment]
I can confirm this same issue. When calling createInstance({name:'some-name'}); on safari mobile instead of returning the instance of the existing DB, localforage will create a new instance with the same name and same data. I'm not sure about the storage size impacts yet but it does seem concerning. You can recreate by emulating an iphone, or connecting to a site from an iphone and then monitoring the index databases in the safari web inspector on a Mac.
