### ISSUE TITLE
@types/localforage@0.0.34 missing index.d.ts

### ISSUE THREAD

**Issue by ZenSoftware** [localForage/localForage#727]
Upgrading from 0.0.33 to 0.0.34 removes the index.d.ts for the Typscript typings for the npm package: `@types/localforage`

**System configuration:**
Windows 10
node v7.10.0
npm v4.2.0

**Comment by thgreasi** [comment]
The respective `@types` package isn't maintained by any of the team members as far as I know, even though we have contributed a few times.
Since v1.5.0 the typings are part of this repo and I would strongly suggest you to use those and drop the `@types`.
Curiously I can't find https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/localForage any more.

**Comment by thgreasi** [comment]
It seems that they also added a README in the `@types/localforage` v0.0.34 package that states that localforage now provides its own typings, so v0.0.34 seems like a "gravestone" release. You should obviously either  update to LF 1.5 or stick with v0.0.33.
