### ISSUE TITLE
[Feature] add an expiration date for cached items

### ISSUE THREAD

**Issue by ctf0** [localForage/localForage#774]
is there a way to add an expiration date to the cached/stored items so it can be cleared automatically ?

**Comment by thgreasi** [comment]
Since the various browser storage methods aren't designed primarily for caching but are general purpose implantations this isn't backed in, neither in the browser storage implementations nor in localforage implementations. I would suggest to create a different helper service for your data access calls, which would wrap your data in an other object containing such lifetime statistics (create date, expression date).

**Comment by ferco0** [comment]
do something like that

export default {
    get: async (key) => {

        let { expire, value } = await localForage.getItem(key);

        if(expire < Date.now()){
            localForage.removeItem(key);
            return null;
        }
        
        return value;

    },
    set: async (key, value, expire = false) => {

        if(expire && typeof expire === 'number')
            expire = Math.round(expire * 1000 + Date.now()); // * 1000 to use seconds

        return await localForage.setItem(key, { value, expire });

    }
}

**Comment by lwyj123** [comment]
It will be nice If localforage has official support for expiration.

**Comment by tofumatt** [comment]
As mentioned by @thgreasi, this isn't something we want to support in core as we've designed localForage to be a bit more general-purpose. Adding an expiration mechanism/helper should be straightforward, but as it's more useful for caching than generic storage, I don't think it's appropriate to include in localForage core.

**Comment by ferco0** [comment]
I think the generic storage some times need expiration too.

**Comment by thgreasi** [comment]
I'm not 100% sure about that @ferco0 :thinking: 
None of the generic browser storage mechanisms (localStorage, webSql, IndexedDB) have the concept of expiration in them, nor the filesystem on my computer.
While having the cache user case in mind though, it definitely makes sense to support expiration dates for keys. Perhaps this could be implemented as an extension for localForage.

Skeleton of a backwards compatible solution:
Given a user defined localForage instance "A" with a store "Sa", the extension should maintain a separate localForage instance "A-exp" with its own store "Sa-exp", that for each key of "A" that needs to have an associated expiration, it will hold the expiration date using the same key on "A-exp".
The extension would extends the `setItem()` method to allow amn optional object third argument that will look like: `setItem('test', 'testValue', { expiration: 1605021779755 });` .

**Comment by ferco0** [comment]
what i want to say is that, us developers, sometimes need this feature.

**Comment by LuudJanssen** [comment]
I went ahead and created a wrapper around localforage that adds this capability called "[localforage-cache](https://github.com/LuudJanssen/localforage-cache)".

**Comment by bryik** [comment]
> I'm not 100% sure about that @ferco0 🤔
> None of the generic browser storage mechanisms (localStorage, webSql, IndexedDB) have the concept of expiration in them, nor the filesystem on my computer.

Cookies do.

**Comment by tofumatt** [comment]
Cookies aren't a storage mechanism, or at least not like that. They're a way for a client and a server to exchange information and maintain state in an otherwise stateless transaction.

Sure, you can use cookies as storage the same way you can use generic browser storage mechanisms (localStorage, WebSQL, IndexedDB) to store a JWT and maintain state with an API, but the **design of cookies isn't to be generic storage.** For instance: _cookies usually have a storage limit of about 4kB_, compared to localStorage's 5MB. Even the 5MB offered by localStorage isn't amazing, but it's orders of magnitude better and illustrates why cookies shouldn't be considered a generic storage mechanism. You'd struggle to cache a single image file or even a small cache of API/app state data for a modest app in 4kB.

So: I don't think it's constructive to bring them up in this discussion, particularly in an issue that's been closed as something core of localForage doesn't aim to fix and with a contributor pointing out they released a library with this feature: https://github.com/localForage/localForage/issues/774#issuecomment-599208849.

**Comment by bryik** [comment]
> Cookies aren't a storage mechanism

I think we'll have to agree to disagree on that one.

Sorry if my comment wasn't constructive, I'll use LuddJanssen's wrapper or write my own.

**Comment by asiby** [comment]
I don't get it. What all this resistance against natural evolution. Sure, thanks for creating this library. But ultimately a library is nothing if it doesn't fulfill its user's needs. Features that come out of any library are consumer-driven. If the very people who have decided to trust and use this library are asking for a feature, why is it being shut down with such energy?

Whether the underlying storage layers are using an expiration date or not, that should not be a justification for not implementing it. For instance, many things now exist in Javascript because they grew in popularity thanks to some open source libraries. For instance, there is a great chance that we will soon has LESS or SASS style CSS preprocessor available in web browsers and Chrome already has some experimental flag for using mixins.

Whether the underlying storage layers are using an expiration date or not, that should not be a justification for not implementing it. For instance, many things now exist in Javascript because they grew in popularity thanks to some open source libraries. For instance, there is a great chance that we will soon have LESS or SASS style CSS preprocessor available in web browsers and Chrome already has some experimental flag for using mixins.

1. I need to store a lot of data to avoid requesting them again from a given user on the same computer. The stored data is not sensitive.
2. When the user logs out, and another user logs in, the data for the new user should be separate from that of the previous one. And this scenario should scale up if more that one user routinely accesses that computer.
3. If one of the previous users does not connect for an extended amount of time, then the corresponding data should be removed

The data does not need to be automatically garbage collected. But it can be done opportunistically by the localForage library on access (read or write) in an efficient manner with little impact of the page's performance. But that is an implementation detail that is out of scope for now. It would seem like @LuudJanssen already did it anyway.

The main message I was to pass along is that there are many libraries and software out there that led to the creation of even better forks because they didn't listen to the developers that were using them in a first place. Checkout MySQL vs MariaDB for instance. MariaDB is by a landslide more feature-rich than MySQL and depending on which version of MySQL you are using, MariaDB is a drop-in replacement.

**Comment by LuudJanssen** [comment]
I'll chip in real quick, because of my efforts to create the `localforage-cache` package.

Surprisingly, I think I actually agree with @tofumatt and @thgreasi here. Libraries need to set their boundaries of what to support and what not to support. React could add a component library to their core react implementation, but they don't, because it's out of the scope of the library.

Similarly, I think Localforage's soul purpose is to abstract away API's for different browser storage solutions and create one unified API. It's purpose is not to add features on top of these storage API's, like expiry. 

Don't get me wrong, there's clearly a need to be able to set expiry dates for browser storage entries, else I wouldn't have created the wrapper. I just think that it would make more sense to create a separate package which uses `localforage` underwater, but adds caching functionality on top of it (with expiry dates for example). That way `localforage` can keep its purpose as a library to unify browser storage API's, and another package has the purpose to create a cross-browser cache storage.

I get what you're saying @asiby, but in this case I think localforage is not really comparable to MySQL, because MySQL was *designed* and *intended* to have a lot of features. Localforage's use case is just different, because it's intended to do one thing, and do that thing very very good, which is to provide a generic API for browser storage solutions. 

I think this issue / discussion is actually a good sign of the need for a new open source project which creates a generic caching solution for the browser. [localforage-cache](https://github.com/LuudJanssen/localforage-cache) isn't that, but it might be a start for someone looking to create such a package.

**Comment by tofumatt** [comment]
Yeah, to be clear, I'm working on a new site for localForage and want to feature plugins, extensions, and other libraries that it works well with. `localforage-cache` would be on that list for sure. I like the idea of that library, it's just that it isn't a feature that:

1. all users require
2. is better-implemented in the core library (or can only be implemented by the core library)
3. is trivial to maintain by the core maintainers (@thgreasi and myself)
4. is in the scope of what the core maintainers want localForage to be

It's really lovely to see libraries like a caching library come about using localForage, but implementing it in the core of the library doesn't have any clear benefits in usage to me, but is a burden for the core maintainers and extra complexity for a reduced use-case.

I'm very happy and not resistant to seeing the abilities of localForage grow, but please note that we don't even include features like `getItems` in localForage core, but rather as separate modules: https://github.com/localForage/localForage-getItems. We consider that a localForage-backed repo, but we don't ship it in core because we don't think it covers the use-case for the broadest of localForage users. I've used our extensions to localForage, but only in a fraction of apps I've used the very core of localForage in.

So it's a balancing act, and here we're saying "not in core". But we've always said that we'll happily (and do) promote third-party extensions and tools. We are also open to including them in the localForage organisation implying more "official support" if the conditions are right.

I think that's all to say on the subject, but thanks for everyone's feedback. Not resisting more features, but trying to direct them to the right place 🙂

**Comment by asiby** [comment]
Thanks guys for the explanations. I am now convinced that you did the right thing. Keep up the good work.
