### ISSUE TITLE
Can different stores use different drivers in localForage ?

### ISSUE THREAD

**Issue by subhranshudas** [localForage/localForage#823]
I am trying to use `localForage`. After going through docs, this is how i am using to create store-

`storage.js`

```
 import localforage from 'localforage';
   
 async function createStore(storeName, driver) {
    try {
        await localforage.setDriver( [localforage[driver]] );
        await localforage.setItem(storeName, ['initial value']);
        const readValue = await localforage.getItem(storeName);
        return Promise.resolve(readValue);
    } catch (err) {
        return Promise.reject(err);
    }
}
```

and inside my APP i am calling 
```
await Storage.createStore('store123', 'INDEXEDDB');
Storage.getFromStore('store123');
```
my question is can i create multiple stores which will have different storage mechanism in place and one not affecting the other. something like -
```
await Storage.createStore('store123', 'INDEXEDDB');  // in Web Workers
await Storage.createStore('store456', 'LOCALSTORAGE');  // in some other part of APP not using Web Worker
await Storage.createStore('store789', 'WEBSQL'); // in another part of APP not using Web Worker
```

will each of these stores ([store123, store456, store789]) have their storage mechanism independent of each other and use exclusively whatever mechanism is passed when creating them.

The reason i am asking is in my APP i am using Web Workers and i want some "Web Storage" mechanism in place. But as per https://nolanlawson.github.io/html5workertest/  localStorage is not supported in Web Workers so i want to fallback for my `stores` which are used in Web Workers to `INDEXEDDB` but have `Storage.js` the flexibility to create other `stores` which support other mechanisms like `localStorage` to other pieces of the APP which are not running in the Web Worker.

Ref- https://github.com/nolanlawson/promise-worker/issues/25

**Comment by subhranshudas** [comment]
Follow up question on above - what is the persistance of `indexedDB`. I mean is the data in `indexedDB` wiped out when -
1. user closes the tab.
2. user closes the browser.
3. user shuts down the machine.

Thanks.

**Comment by thgreasi** [comment]
The data will be independent between the different drivers, given that there is browser support (you should check that before). On the other hand you should be using `createInstance()` in your `createStore` method, otherwise you will be operating on a single driver and localforage instance from all parts of your app.
Indexeddb should persist in all cases mentioned, except if the user is on private browsing mode or decides to cleanup local date, or the browser works with low available disk space and runs a cleanup of local data.

I would suggest you to not try forcing a specific driver for each part of your app, but instead pass the `store` and/or `storeName` props in your `createInstance()`call as a better way to achieve data isolation. Each localforage instance with end up using the most appropriate driver depending on the environment it will be used and you can avoid doing this yourself, since this is something that localforage is already doing out of the box.
