### ISSUE TITLE
HTMLImageElement object could not be cloned.

### ISSUE THREAD

**Issue by zjhou** [localForage/localForage#832]
Hi.
when i use `localforage.setItem('img', image)` i got this error:
```
Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': HTMLImageElement object could not be cloned.
```

**Comment by thgreasi** [comment]
I think that's fair enough. You should get the binary blob of the image pointed in the src and call `setItem()` on that one instead of the DOM element. Here is [our respective test case](https://github.com/localForage/localForage/blob/55db1ef633af28abe98ea0baf68fa1c24566f282/test/test.datatypes.js#L366).
