### ISSUE TITLE
Transpile modules

### ISSUE THREAD

**Issue by haldunatar** [localForage/localForage#838]
Please transpile the publish source! At this moment, the untranspiled localForage source in the node_modules  breaks jest tests..

**Comment by tofumatt** [comment]
Could you provide more info and an example of what tests are breaking for you? Steps to reproduce will help us understand and fix any issues.

For what it’s worth though, I’ve worked on several projects using Jest and localForage without issue...

**Comment by thgreasi** [comment]
We indeed also include the es6 sources in the `src/` folder, but the `main` field of `package.json` points to the es3 transpiled sources found in the `dist/` folder.
How do you import LF? Do you explicitly point to the `src` folder? If not, then the `src/` folder of LF shouldn't be referenced at all.
If jest just parses everything in the node_modules, that would be bad.

**Comment by ianmcnally** [comment]
We hit this problem and realized we weren't ignoring node_module transform in jest.

```js
// jest.config.js
{
    transformIgnorePatterns: ['node_modules'],
}
```

**Comment by haldunatar** [comment]
@thgreasi I actually import ngForage
```
import { NgForage } from 'ngforage';
```
and localforage is imported via ngforage. My point is that localforage files are published as untranspiled. Exp:

> node_modules/localforage/src/utils/serializer.js

@ianmcnally I tried that but it didn't help..
I fixed it at the end with mocking 'serializer.js' with using **moduleNameMapper**
```
moduleNameMapper: {
  'app/(.*)': '<rootDir>/src/app/$1',
  serializer: '<rootDir>/jest-mocks/serializer.js',
},
```

**Comment by thgreasi** [comment]
As far as this module is concerned, only the dist file pointed by the `main` field of the `package.json` should be used. All other files are there for those who want to explicitly load the es6 sources and should normally be ignored since they could be anything, from es6 to coffeescript, Typescript or even webassembly.

If you check https://unpkg.com/ngforage@3.4.0/bundles/ngforage.umd.js you will notice the following on line 67:
`var serializer$ = require('localforage/src/utils/serializer');`
That's probably the line that's causing your issues. We do provide `localforage.getSerializer()` as a way to use the LF's serializer from the dist files as well. Please file an issue on ngforage for this, since such a umd dist can't really work on an environment that doesn't provide a `require` method (eg: window).

**Comment by afilp** [comment]
@thgreasi I have the same problem, exactly due to a similar line:

```
return System["import"]("./../../node_modules/localforage/src/utils/serializer").then(function(lib) {
                    dbInfo.serializer = lib;
                    return Promise.resolve();
                });
```

I am not sure how should I change this line so that it does not cause problems to the compilation.

Thanks for any ideas!

**Comment by thgreasi** [comment]
@afilp as far as I can tell, you are using an older version of LocalForage and you are trying to import a file from the src instead of the dist. This line was transpiled as part of our could process and it's not expected to be consumed by your project directly. You should do one of the following:
* Point to the dist files instead of the src ones
* Upgrade LocalForage to newer version that's not using System.import
* Try using https://github.com/thgreasi/babel-plugin-system-import-transformer as part of your build process

Just to be clear, IMO the correct solution is the one in the first bullet.

**Comment by thgreasi** [comment]
Oh I just saw the `./../../node_modules` part, so I guess that's one of your libraries references LocalForage. Bumping LocalForage version should still fix the issue, since System.import isn't used in newer versions. If you still have an issue, then please open an issue in the project that does the aforementioned LocalForage import
