### ISSUE TITLE
throttling read/write to localStorage

### ISSUE THREAD

**Issue by gloss-water** [localForage/localForage#848]
Hi! I haven't looked too deeply, so sorry if this is answered somewhere already.

For when/if you end up using localStorage, is there any concept of "throttling" saves?  I'm assuming this is something we'd have to implement on the user side since localForage shouldn't really be making those decisions, but I wouldn't want to implement it for all calls -- for example, if indexedDB is found I wouldn't care about the throttling.  I guess you could just check .supports.

My question may have just turned into a rubber ducky session but I'd appreciate any input anyway. :)

**Comment by thgreasi** [comment]
@gloss-water yea, LF doesn't do any throttling.
The approach you suggest totally makes sense to me :+1: 
I could also suggest you that instead of creating a wrapper around LF, you could just create an plugin that wraps the appropriate methods, after your LF instance becomes `.ready()` and you are using the desired driver.
You can take a look on how [localforage-observable does exactly that](https://github.com/localForage/localForage-observable/blob/c1d8432a7cc41edbccafe5ce6050c32b551c625d/lib/index.ts#L84-L103).
