### ISSUE TITLE
 How to get callback content in a function?

### ISSUE THREAD

**Issue by amhoho** [localForage/localForage#860]
demo:
```js
function getValue(key){
//api
localforage.getItem(key).then(function (value) {
return value;
}).catch(function(err) {
return false;
})
// How to get `value` or `false` here?
}
```

**Comment by sinharaksh1t** [comment]
I don't know if this would solve your concern, but the 'hacky' workaround would be to have a variable on a broader scope that you can return through the function:
```
function getValue(key) {
  let result;
  localforage.getItem(key).then(function (value) {
    result = value;
  }).catch(function(err) {
    result = false;
  })
  return result;
}
```

**Comment by thgreasi** [comment]
Hi,
Unfortunately you can't return the result in a synchronous way, since `getItem` is asynchronous.
You will either have to return the promise that `getItem` returns and write a promised based implementation or pass a callback to your `getValue`.

If you are using babel or any modern code per-processor/transpiler (babel/typescript) you could make your code look more synchronous using `await`. 
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
