### ISSUE TITLE
Why promise of setItem pending too long?

### ISSUE THREAD

**Issue by ducpt1** [localForage/localForage#865]
I tried this code

```js
localforage.setItem('my array', [1, 2, 'three']).then(function(value) {
    // This will output `1`.
    console.log(value[0]);
}).catch(function(err) {
    // This code runs if there were any errors
    console.log(err);
});
```

I saw in console had promise with status "pending".
I waited for a while but it did'nt console log 1

Sorry for my bad English!!!

**Comment by tofumatt** [comment]
I went to https://localforage.github.io/localForage/ and ran the code you pasted here: a console log statement appeared with the text "1", which is what `value[0]` is in your code:

<img width="530" alt="screenshot 2018-12-27 11 50 03" src="https://user-images.githubusercontent.com/90871/50479279-a6a09c00-09cd-11e9-85d0-953859e87aee.png">

The promise will appear in the console as "Pending" at first because it's being returned to the browser console before it's completed, but you can see the actual console log statement being run afterward 😄
