### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by darknblack** [localForage/localForage#908]
It would be great if this package will support react native asyncstorage. Thank you

**Comment by thgreasi** [comment]
Hi @darknblack ,
This sounds really interesting and it shouldn't too had to implement as a custom driver for localforage.
If anyone is willing to try this, I expect that their code should look a bit like https://github.com/localForage/localForage-sessionStorageWrapper , essentially just properly setting the "_dbInfo.db"  property.

**Comment by fohletex** [comment]
Hi @darknblack and @thgreasi,

we developed a solution for this problem, which might help you. Glad to read your feedback, if it helps.

Cheers!

https://github.com/aveq-research/localforage-asyncstorage-driver

**Comment by thgreasi** [comment]
That's nice @fohletex :+1: 
I would be happy to link to that repo from our README and close this issue in case you are willing to open such a PR.

PS: It looks like you could inherit some pieces of the implementation from LF's async storage driver and just have to override a few methods in your custom driver, similarly to how https://github.com/thgreasi/localForage-cordovaSQLiteDriver/blob/master/lib/localforage-cordovasqlitedriver.js does it.

**Comment by fohletex** [comment]
Thanks @thgreasi for your quick feedback. I am glad to see that it is helpful.

I wasn't sure where to link the repo in the README, since all other custom drivers are listed within the wiki. Thus, I added the link to our repository here:

https://github.com/localForage/localForage/wiki/Custom-Drivers

From my side the issue can be closed or do you really mean linking it in the README itself?

Regarding your other comment: I will have a look where we can better optimize the code. Expecting to solve it within the next week.

See you!

**Comment by thgreasi** [comment]
You're right @fohletex .
I thought we listed custom drivers as well, but it seems that we only point to the wiki.
Let's close this :+1:

**Comment by fohletex** [comment]
:+1: Perfect. Thanks!
