### ISSUE TITLE
Is localForage abandoned ?

### ISSUE THREAD

**Issue by gotenxds** [localForage/localForage#915]
It does not seem to be maintained, last commit was a year ago

**Comment by tofumatt** [comment]
It is not: the core of localForage v1 is largely "feature-complete" but is extended by localForage plugins available in other repositories in the organisation: https://github.com/localForage/

The last commit was last month and there is continued issue and PR work, but because it's quite stable our plans for v2 are largely about internal refactoring. You can see the continued commits here: https://github.com/localForage/localForage/commits/master
