### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by nainardev** [localForage/localForage#935]
Its currenly **8.6 kB gzipped** (https://bundlephobia.com/result?p=localforage@1.7.3)

Main reason for this size is due to *supporting callback version*. **Promise API** is currently supported in [94.4% of the browsers](https://caniuse.com/#search=promise). We can use [Promise polyfill](https://github.com/taylorhakes/promise-polyfill) for IE 11.

This library's size could be reduced by as much as 50% by supporting **only** Promise API

**Comment by tofumatt** [comment]
localForage already ships with a Promises polyfill, but the reason for supporting the callback API is due to when localForage was released and wanting to provide an easy onramp to usage without requiring webpack/babel which, at the time of first release, weren't as common.

That said, this feature is on the roadmap: #535.
