### ISSUE TITLE
Localforage can be used with ReactJs?

### ISSUE THREAD

**Issue by vijay9756** [localForage/localForage#944]
I want to use localforage with ReactJs app, but I didn't found any solution and I am struggling with, have any way to use it with ReactJs?

**Comment by tofumatt** [comment]
See #900 and #897; localForage is already used in React applications (for instance the Mozilla Add-one website) because it's a plain JavaScript library. You can import localForage as you would any other library you install with `npm install`.

You can use `localforage` inside your React components like any other JS library.
