### ISSUE TITLE
set key-value pair in bulk should be provided in localstorage driver(database)

### ISSUE THREAD

**Issue by himanshu199728** [localForage/localForage#952]
Currently, we are storing key-value pair data and calling for each time each if we want to set multiple key-value pairs at a time.

**Currently**: setItem(<key>, <value>);

**My Expectation**: setItems([{key:<key>, value: <value>}, [key :<key>, value :<value>]...]);

Sometimes we require to cache more than one DB connection details to store or multiple photos data as blob store in bulk in storage.

**Comment by thgreasi** [comment]
Hi,
Have you checked https://github.com/localForage/localForage-setItems ?
It sounds like it does exactly what you need for all supported drivers.
We decided to not make this part of the core localforage api, at least initially, since there was also a different approach in the works at that point.

I will close this for now, since I think that the extension covers this use case, but feel free to re-open.

**Comment by himanshu199728** [comment]
#953. Can we look into this? or this is a useless change.
