### ISSUE TITLE
Get Items for those keys that contain given key input as substring

### ISSUE THREAD

**Issue by himanshu199728** [localForage/localForage#959]
Here I want to get all keys value pair in which keys are contain given input key as a substring
For eg;
In localStorage driver, there are Items store for students with keys as 'student-class-1, student-class-2, etc and for teachers keys like teacher-class-1, etc.
So to get data for only those key which contain 'student' as a substring at one shot.

**Comment by himanshu199728** [comment]
@thgreasi Can we add this feature in this library.

**Comment by tofumatt** [comment]
localForage doesn't support this "out-of-the-box", but because it supports extensions, you can use https://github.com/localForage/localForage-getItems to get all items at once (and then filter the results) or use https://github.com/localForage/localForage-startsWith to get all items that start with a key.

You could also use either of those libraries as the basis to build your own extension that allowed you to get any key that matches a substring, instead of just starting with one.

So we probably wouldn't add something like this to the core library (at least not in v1), but we do support it with extensions, and if the current ones don't work exactly for you, it should be straightforward to use them as a basis for your own extensions 🙂

**Comment by himanshu199728** [comment]
But how will I make this extension a part of localForage repository

**Comment by tofumatt** [comment]
Once you make the extension, you can publish it as your own npm module to start with, as it doesn't need to be part of the localForage repo/organisation to work. Usually the modules in our organisation are maintained by localForage authors, but it's okay to publish it as a third-party extension 🙂

**Comment by himanshu199728** [comment]
Cool 😊👍
