### ISSUE TITLE
[Question] Is making new instances for each thing you want to store faster for asynchronous writing?

### ISSUE THREAD

**Issue by chausies** [localForage/localForage#974]
For IndexedDB, [this Stack Overflow answer](https://stackoverflow.com/a/28036121/1114253) says that one should create a new database for each `objectStore` they wish to create (as opposed to putting all the object stores on one database), because then the different `objectStore`s can be written to simultaneously without blocking access to each other.

My question is if local forage behaves similarly? Is it the case if I don't create a new instance for `objectStore`-like set of data, then different writes will block each other's access and slow things down?

Sorry if the Github issues isn't the proper place to ask this question. And many thanks for this fantastic library, by the way. You're doing God's work.

**Comment by tofumatt** [comment]
GitHub is the best place for these questions, no worries! I'm excited for GitHub Discussions, but for now an issue is fine 😄 

localForage supports multiple databases and multiple `objectStore`s, so you can use multiple to avoid blocking writes. To create multiple `objectStore`s use the `storeName` config value as outlined here: https://localforage.github.io/localForage/#multiple-stores

From what I recall I don't think you'll see a major performance difference if you aren't making a LOT of read/writes than if you just used one `storeName`, but it's relatively straightforward to use multiple instances with different stores if you want, so feel free to try it out. If you notice it's a lot more performant feel free to let us know in the issue here 🙂 

Glad you're liking the library, thanks! 👍
