### ISSUE TITLE
Can support sync in getItem ?

### ISSUE THREAD

**Issue by haoxutong** [localForage/localForage#981]

**Comment by tofumatt** [comment]
Do you mean a synchronous `getItem` call without `await`/Promises? No, that's fundamentally incompatible with the WebSQL and IndexedDB APIs, as well as the aim of localForage.

For synchronous storage you'll want to stick with `localStorage` directly. But if you don't like the Promises API, look into `async`/`await` to make the code _read_ like it's synchronous 😄

**Comment by muuvmuuv** [comment]
I do think this would be nice, but only for localstorage, so I can have advantage of version, name, storeName and so on and localforage is my api wrapper. In some cases I use createInstance for only localstorage where I have to use sync storages due to the framework and how it initializes some dependencies.
